-- MySQL Script generated by MySQL Workbench
-- Tue Mar 12 12:20:28 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema colegio2407
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema colegio2407
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `colegio2407` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `colegio2407` ;

-- -----------------------------------------------------
-- Table `colegio2407`.`alumnos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`alumnos` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`alumnos` (
  `clave_alu` VARCHAR(20) NOT NULL,
  `clave_admin` VARCHAR(20) NOT NULL,
  `ap_paterno` VARCHAR(50) NOT NULL,
  `ap_materno` VARCHAR(50) NULL DEFAULT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `curp` VARCHAR(18) NOT NULL,
  `peso` DECIMAL(6,2) NULL DEFAULT '0.00',
  `estatura` DECIMAL(6,2) NULL DEFAULT '0.00',
  `direccion` VARCHAR(100) NULL DEFAULT NULL,
  `colonia` VARCHAR(100) NULL DEFAULT NULL,
  `cp` VARCHAR(6) NULL DEFAULT NULL,
  `ciudad` VARCHAR(100) NULL DEFAULT NULL,
  `id_estado` INT NULL DEFAULT NULL,
  `delegacion` VARCHAR(100) NULL DEFAULT NULL,
  `telefono` VARCHAR(20) NULL DEFAULT NULL,
  `celular` VARCHAR(20) NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `status_alu` ENUM('AC', 'BA', 'EX', 'AS') NOT NULL,
  `fedita` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`clave_alu`),
  INDEX `fk_estado_alumno_idx` (`id_estado` ASC) VISIBLE,
  CONSTRAINT `fk_estado_alumno`
    FOREIGN KEY (`id_estado`)
    REFERENCES `colegio2407`.`estados` (`id_estado`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`alumno_salon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`alumno_salon` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`alumno_salon` (
  `id_salon` INT NOT NULL,
  `id_curso` VARCHAR(5) NOT NULL DEFAULT '',
  `clave_alu` VARCHAR(20) NOT NULL,
  `nl` INT NOT NULL,
  `activo` INT UNSIGNED NULL DEFAULT NULL,
  PRIMARY KEY (`id_salon`, `id_curso`, `clave_alu`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`cursos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`cursos` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`cursos` (
  `id_curso` VARCHAR(5) NOT NULL,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  `abreviatura` VARCHAR(10) NULL DEFAULT NULL,
  `finicio` DATETIME NULL DEFAULT NULL,
  `ffin` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id_curso`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`estados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`estados` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`estados` (
  `id_estado` INT NOT NULL,
  `estado` VARCHAR(50) NULL DEFAULT NULL,
  `abreviatura` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_estado`),
  UNIQUE INDEX `estado_UNIQUE` (`estado` ASC) VISIBLE,
  UNIQUE INDEX `abreviatura_UNIQUE` (`abreviatura` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1;


-- -----------------------------------------------------
-- Table `colegio2407`.`evaluaciones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`evaluaciones` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`evaluaciones` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `clave_alu` VARCHAR(20) NULL DEFAULT NULL,
  `id_curso` VARCHAR(5) NULL DEFAULT NULL,
  `id_salon` INT UNSIGNED NULL DEFAULT NULL,
  `clave_mat` VARCHAR(10) NULL DEFAULT NULL,
  `calificacion` INT UNSIGNED NULL DEFAULT NULL,
  `fmod` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 259617
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`grados`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`grados` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`grados` (
  `id_grado` INT NOT NULL,
  `nombre` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`id_grado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`materias`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`materias` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`materias` (
  `clave_mat` VARCHAR(10) NOT NULL,
  `id_nivel` INT NOT NULL,
  `id_grado` INT NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `descripcion` VARCHAR(50) NOT NULL,
  `abreviatura` VARCHAR(10) NOT NULL,
  `promedia` INT NOT NULL,
  `orden` INT NOT NULL,
  PRIMARY KEY (`clave_mat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`niveles`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`niveles` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`niveles` (
  `id_nivel` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL DEFAULT NULL,
  PRIMARY KEY (`id_nivel`))
ENGINE = InnoDB
AUTO_INCREMENT = 8
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`pagos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`pagos` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`pagos` (
  `clave_alu` VARCHAR(20) NOT NULL,
  `sucursal` VARCHAR(6) NOT NULL,
  `ref_numerica` VARCHAR(10) NOT NULL,
  `ref_alfanumerica` VARCHAR(20) NOT NULL,
  `pago` FLOAT NOT NULL,
  `fecha_pago` DATETIME NOT NULL,
  `origen` VARCHAR(1) NOT NULL,
  `fecha_op` DATETIME NOT NULL,
  `id_curso` VARCHAR(5) NULL DEFAULT NULL,
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 29216
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`profesores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`profesores` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`profesores` (
  `clave_prof` INT NOT NULL,
  `apellido_p` VARCHAR(30) NOT NULL,
  `apellido_m` VARCHAR(30) NOT NULL,
  `nombres` VARCHAR(30) NOT NULL,
  `sexo` VARCHAR(1) NOT NULL,
  `curp` VARCHAR(18) NOT NULL,
  `edocivil` VARCHAR(1) NOT NULL,
  `lugarnac` VARCHAR(30) NOT NULL,
  `gradoestudio` VARCHAR(15) NOT NULL,
  `profesion` VARCHAR(50) NOT NULL,
  `cedula` VARCHAR(30) NOT NULL,
  `calle` VARCHAR(50) NOT NULL,
  `colonia` VARCHAR(50) NOT NULL,
  `cp` VARCHAR(8) NOT NULL,
  `ciudad` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(4) NOT NULL,
  `municipio` VARCHAR(50) NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  `celular` VARCHAR(20) NOT NULL,
  `email` VARCHAR(50) NOT NULL,
  `fnac` DATETIME NOT NULL,
  `fedita` DATETIME NOT NULL,
  `cargo` VARCHAR(6) NOT NULL DEFAULT '0',
  PRIMARY KEY (`clave_prof`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`profesor_grupo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`profesor_grupo` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`profesor_grupo` (
  `clave_prof` INT NOT NULL,
  `id_curso` VARCHAR(5) NOT NULL,
  `clave_mat` INT NOT NULL,
  `id_salon` INT NOT NULL,
  `fecha` DATETIME NOT NULL,
  PRIMARY KEY (`clave_prof`, `id_curso`, `id_salon`, `clave_mat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


-- -----------------------------------------------------
-- Table `colegio2407`.`salones`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `colegio2407`.`salones` ;

CREATE TABLE IF NOT EXISTS `colegio2407`.`salones` (
  `id_salon` VARCHAR(11) NOT NULL,
  `id_grado` INT NOT NULL,
  `id_nivel` INT UNSIGNED NULL DEFAULT NULL,
  `observaciones` VARCHAR(20) NOT NULL,
  `tipo_grupo` VARCHAR(12) NOT NULL,
  `id_curso` VARCHAR(5) NULL DEFAULT NULL,
  PRIMARY KEY (`id_salon`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb3;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
